#This file contains a function that calls scripts in an ordered way when the "MINT" button is called on PATH/gui_main.py
#The existance of this file is due to the critical nature in which the scripts are ran 
import sys
sys.path.append("metadata_info")
import json
import requests
from metadata_template import nft_metadata
from brownie import NftFactory, ERC20Token
from scripts.mint_tokens import mint_erc20_tokens
from scripts.utils import get_account, network, config
from scripts.upload_image_to_ipfs import ipfs_upload
from pin_metadata_and_mint import upload_to_pinata

# Returns the current total supply of tokens
def get_total_supply():
    account = get_account()
    token_contract = ERC20Token[-1]
    get_total_supply = token_contract.totalSupply()
    print(f"  Total supply: {get_total_supply}")

# Returns the random number generated by the VRFCoordinator
def get_random_result():
    account = get_account()
    token_contract = ERC20Token[-1]
    get_random_number = token_contract.randomResult()
    print(f"  Random number returned: {get_random_number}")

def main():
    mint_erc20_tokens()
    ipfs_upload()
    upload_to_pinata()