from brownie import ERC20Token, config, network, project
from scripts.utils import get_account
from Gui.gui_main import *
# Creates random amount of tokens. The number of tokens created
# is based on the random number returned from VRFCoordinator.
# This number will always be from 1 - 15 
# More info on randomness can be found at: https://docs.chain.link/docs/get-a-random-number/
def mint_tokens():
    account = get_account()
    token_contract = ERC20Token[-1]
    print(f"  Minting tokens form {token_contract}")
    tx = token_contract.getRandomNumber({"from": account})
    print(f"  Chainlink VRF called\nVerifying random number...")

# Returns the current total supply of tokens
def get_total_supply():
    account = get_account()
    token_contract = ERC20Token[-1]
    get_total_supply = token_contract.totalSupply()
    print(f"  Total supply: {get_total_supply}")

# Returns the random number generated by the VRFCoordinator
def get_random_result():
    account = get_account()
    token_contract = ERC20Token[-1]
    get_random_number = token_contract.randomResult()
    print(f"  Random number returned: {get_random_number}")

# Invokes the above functions 
def main():
    mint_tokens()
    #get_total_supply()
    #get_random_result()
