# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiV2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.leftGroupBox.setGeometry(QtCore.QRect(10, 10, 411, 421))
        self.leftGroupBox.setObjectName("leftGroupBox")
        self.stageButton = QtWidgets.QPushButton(self.leftGroupBox)
        self.stageButton.setGeometry(QtCore.QRect(310, 370, 91, 41))
        self.stageButton.setObjectName("stageButton")
        self.styleTwoCheckBox = QtWidgets.QCheckBox(self.leftGroupBox)
        self.styleTwoCheckBox.setGeometry(QtCore.QRect(230, 390, 70, 17))
        self.styleTwoCheckBox.setAutoExclusive(True)
        self.styleTwoCheckBox.setObjectName("styleTwoCheckBox")
        self.styleOneCheckBox = QtWidgets.QCheckBox(self.leftGroupBox)
        self.styleOneCheckBox.setGeometry(QtCore.QRect(230, 370, 70, 17))
        self.styleOneCheckBox.setAutoExclusive(True)
        self.styleOneCheckBox.setObjectName("styleOneCheckBox")
        self.leftLabel = QtWidgets.QLabel(self.leftGroupBox)
        self.leftLabel.setGeometry(QtCore.QRect(10, 30, 390, 330))
        self.leftLabel.setAcceptDrops(True)
        self.leftLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.leftLabel.setText("")
        self.leftLabel.setTextFormat(QtCore.Qt.AutoText)
        self.leftLabel.setScaledContents(True)
        self.leftLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.leftLabel.setOpenExternalLinks(False)
        self.leftLabel.setObjectName("leftLabel")
        self.browseButton = QtWidgets.QPushButton(self.leftGroupBox)
        self.browseButton.setGeometry(QtCore.QRect(10, 370, 91, 41))
        self.browseButton.setObjectName("browseButton")
        self.rightGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.rightGroupBox.setGeometry(QtCore.QRect(430, 10, 411, 421))
        self.rightGroupBox.setObjectName("rightGroupBox")
        self.rightLabel = QtWidgets.QLabel(self.rightGroupBox)
        self.rightLabel.setGeometry(QtCore.QRect(10, 30, 390, 330))
        self.rightLabel.setAcceptDrops(True)
        self.rightLabel.setText("")
        self.rightLabel.setScaledContents(True)
        self.rightLabel.setOpenExternalLinks(False)
        self.rightLabel.setObjectName("rightLabel")
        self.mintButton = QtWidgets.QPushButton(self.rightGroupBox)
        self.mintButton.setGeometry(QtCore.QRect(310, 370, 91, 41))
        self.mintButton.setObjectName("mintButton")
        self.deleteButton = QtWidgets.QPushButton(self.rightGroupBox)
        self.deleteButton.setGeometry(QtCore.QRect(10, 370, 91, 41))
        self.deleteButton.setObjectName("deleteButton")

        self.nameInputBox = QtWidgets.QLineEdit(self.rightGroupBox)
        self.nameInputBox.setGeometry(QtCore.QRect(110, 370, 191, 20))
        self.nameInputBox.setObjectName("nameInputBox")
        
        self.descriptionInputBox = QtWidgets.QLineEdit(self.rightGroupBox)
        self.descriptionInputBox.setGeometry(QtCore.QRect(110, 390, 191, 20))
        self.descriptionInputBox.setText("")
        self.descriptionInputBox.setObjectName("descriptionInputBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionDocs = QtWidgets.QAction(MainWindow)
        self.actionDocs.setObjectName("actionDocs")
        self.menuHelp.addAction(self.actionDocs)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.leftGroupBox.setTitle(_translate("MainWindow", "Photo Staging Area"))
        self.stageButton.setText(_translate("MainWindow", "Stage"))
        self.styleTwoCheckBox.setText(_translate("MainWindow", "Cartoonify"))
        self.styleOneCheckBox.setText(_translate("MainWindow", "Borders"))
        self.browseButton.setText(_translate("MainWindow", "Browse "))
        self.rightGroupBox.setTitle(_translate("MainWindow", "Photo Minting Area"))
        self.mintButton.setText(_translate("MainWindow", "MINT"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.nameInputBox.setPlaceholderText(_translate("MainWindow", "NFT name..."))
        self.descriptionInputBox.setPlaceholderText(_translate("MainWindow", "NFT Description..."))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionDocs.setText(_translate("MainWindow", "Help Document"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
